In [1]:
import os
import glob as glob
import numpy as np
import pandas as pd
import seaborn as sns

In [2]:
folder_vpn = "data\\pcap_to_csv\\vpn"
filepaths_vpn = [i for i in glob.glob(folder_vpn + "\*")]
print(filepaths_vpn)

['data\\pcap_to_csv\\vpn\\vpn_aim_chat1a.pcap_Flow.csv', 'data\\pcap_to_csv\\vpn\\vpn_aim_chat1b.pcap_Flow.csv', 'data\\pcap_to_csv\\vpn\\vpn_bittorrent.pcap_Flow.csv', 'data\\pcap_to_csv\\vpn\\vpn_email2a.pcap_Flow.csv', 'data\\pcap_to_csv\\vpn\\vpn_email2b.pcap_Flow.csv', 'data\\pcap_to_csv\\vpn\\vpn_facebook_audio2.pcap_Flow.csv', 'data\\pcap_to_csv\\vpn\\vpn_facebook_chat1a.pcap_Flow.csv', 'data\\pcap_to_csv\\vpn\\vpn_facebook_chat1b.pcap_Flow.csv', 'data\\pcap_to_csv\\vpn\\vpn_ftps_A.pcap_Flow.csv', 'data\\pcap_to_csv\\vpn\\vpn_ftps_B.pcap_Flow.csv', 'data\\pcap_to_csv\\vpn\\vpn_hangouts_audio1.pcap_Flow.csv']

In [3]:
label = 'vpn'
 
for path in filepaths_vpn:
    filename = (path.split('.')[0]).split('\\')[-1]
    print(filename)
    dummy_df = pd.read_csv(path)
    dummy_df['Label'] = label
    dummy_df.to_csv(os.path.join("data\\all_csvs\\" + filename + '.csv'), index=False)

vpn_aim_chat1a
vpn_aim_chat1b
vpn_bittorrent
vpn_email2a
vpn_email2b
vpn_facebook_audio2
vpn_facebook_chat1a
vpn_facebook_chat1b
vpn_ftps_A
vpn_ftps_B
vpn_hangouts_audio1

In [4]:
folder_non_vpn = "data\\pcap_to_csv\\non_vpn"
filepaths_non_vpn = [i for i in glob.glob(folder_non_vpn + "\*")]
print(filepaths_non_vpn)

['data\\pcap_to_csv\\non_vpn\\aim_chat_3a.pcap_Flow.csv', 'data\\pcap_to_csv\\non_vpn\\aim_chat_3b.pcap_Flow.csv', 'data\\pcap_to_csv\\non_vpn\\email1a.pcap_Flow.csv', 'data\\pcap_to_csv\\non_vpn\\email1b.pcap_Flow.csv', 'data\\pcap_to_csv\\non_vpn\\email2a.pcap_Flow.csv', 'data\\pcap_to_csv\\non_vpn\\email2b.pcap_Flow.csv', 'data\\pcap_to_csv\\non_vpn\\facebook_audio1a.pcap_Flow.csv', 'data\\pcap_to_csv\\non_vpn\\facebook_audio2a.pcap_Flow.csv', 'data\\pcap_to_csv\\non_vpn\\facebook_chat_4a.pcap_Flow.csv', 'data\\pcap_to_csv\\non_vpn\\facebook_chat_4b.pcap_Flow.csv', 'data\\pcap_to_csv\\non_vpn\\facebook_video1a.pcap_Flow.csv', 'data\\pcap_to_csv\\non_vpn\\facebook_video2a.pcap_Flow.csv']

In [5]:
label = 'non_vpn'
 
for path in filepaths_non_vpn:
    filename = (path.split('.')[0]).split('\\')[-1]
    print(filename)
    dummy_df = pd.read_csv(path)
    dummy_df['Label'] = label
    dummy_df.to_csv(os.path.join("data\\all_csvs\\" + filename + '.csv'), index=False)

aim_chat_3a
aim_chat_3b
email1a
email1b
email2a
email2b
facebook_audio1a
facebook_audio2a
facebook_chat_4a
facebook_chat_4b
facebook_video1a
facebook_video2a

In [6]:
Allfilepaths = [i for i in glob.glob("data\\all_csvs" + "\*")]
#combine all files in the list
combined_csv = pd.concat([pd.read_csv(f) for f in Allfilepaths])
# suffle 
combined_csv=combined_csv.sample(frac=1)
#export to csv
combined_csv.to_csv( "data\\vpn-non_vpn.csv", index=False, encoding='utf-8-sig')

In [7]:
combined_csv.head()

,Flow ID,Src IP,Src Port,Dst IP,Dst Port,Protocol,Timestamp,Flow Duration,Tot Fwd Pkts,Tot Bwd Pkts,...,Fwd Seg Size Min,Active Mean,Active Std,Active Max,Active Min,Idle Mean,Idle Std,Idle Max,Idle Min,Label
1665,131.202.240.102-224.0.0.252-52268-5355-17,131.202.240.102,52268,224.0.0.252,5355,17,25/05/2015 10:32:20 PM,410493,1,1,...,0,0.000000,0.000000,0.0,0.0,0.000000e+00,0.000000e+00,0.0,0.0,non_vpn
434,10.0.2.15-64.4.23.162-15685-40019-17,10.0.2.15,15685,64.4.23.162,40019,17,06/06/2015 12:59:05 AM,8645898,2,4,...,0,717841.000000,0.000000,717841.0,717841.0,7.582491e+06,0.000000e+00,7582491.0,7582491.0,non_vpn
203,131.202.240.45-131.202.240.87-161-61992-17,131.202.240.87,61992,131.202.240.45,161,17,25/05/2015 10:26:43 PM,93682019,168,170,...,0,8126.666667,103.079258,8232.0,8026.0,2.892348e+07,1.861686e+06,30001130.0,26773792.0,non_vpn
1863,131.202.240.185-224.0.0.252-62960-5355-17,131.202.240.185,62960,224.0.0.252,5355,17,25/05/2015 10:26:54 PM,410744,1,1,...,0,0.000000,0.000000,0.0,0.0,0.000000e+00,0.000000e+00,0.0,0.0,non_vpn
65,131.202.240.150-131.202.244.5-51557-53-17,131.202.240.150,51557,131.202.244.5,53,17,30/03/2015 06:12:04 PM,342,0,2,...,0,0.000000,0.000000,0.0,0.0,0.000000e+00,0.000000e+00,0.0,0.0,non_vpn

In [8]:
combined_csv =combined_csv.iloc[: , 7:]

In [9]:
combined_csv.describe()

,Flow Duration,Tot Fwd Pkts,Tot Bwd Pkts,TotLen Fwd Pkts,TotLen Bwd Pkts,Fwd Pkt Len Max,Fwd Pkt Len Min,Fwd Pkt Len Mean,Fwd Pkt Len Std,Bwd Pkt Len Max,...,Fwd Act Data Pkts,Fwd Seg Size Min,Active Mean,Active Std,Active Max,Active Min,Idle Mean,Idle Std,Idle Max,Idle Min
count,1.510000e+04,15100.000000,15100.000000,1.510000e+04,1.510000e+04,15100.000000,15100.000000,15100.000000,15100.000000,15100.000000,...,15100.000000,15100.0,1.510000e+04,1.510000e+04,1.510000e+04,1.510000e+04,1.510000e+04,1.510000e+04,1.510000e+04,1.510000e+04
mean,1.063989e+07,55.253444,59.383179,2.049243e+04,4.281924e+04,75.740066,11.914768,27.426714,19.481411,203.311325,...,39.714901,0.0,1.863704e+05,1.157247e+05,3.569499e+05,9.548589e+04,3.470665e+06,4.701185e+05,3.918540e+06,3.069659e+06
std,2.990688e+07,712.624499,723.160739,6.599299e+05,7.108985e+05,243.131013,28.488607,86.698954,77.207861,418.846641,...,687.622992,0.0,1.360006e+06,1.040143e+06,2.655099e+06,8.841142e+05,1.241610e+07,3.436405e+06,1.361223e+07,1.181102e+07
min,1.000000e+00,0.000000,1.000000,0.000000e+00,0.000000e+00,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.0,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00
25%,7.930000e+02,0.000000,1.000000,0.000000e+00,2.200000e+01,0.000000,0.000000,0.000000,0.000000,22.000000,...,0.000000,0.0,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00
50%,1.311345e+05,1.000000,2.000000,0.000000e+00,1.750000e+02,0.000000,0.000000,0.000000,0.000000,141.000000,...,0.000000,0.0,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00
75%,4.206040e+05,1.000000,2.000000,2.200000e+01,3.772500e+02,22.000000,22.000000,22.000000,0.000000,234.250000,...,1.000000,0.0,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00
max,1.200000e+08,31666.000000,31412.000000,4.131281e+07,4.099927e+07,2676.000000,520.000000,1304.642456,1009.121557,23095.000000,...,31659.000000,0.0,4.218478e+07,4.030572e+07,5.723106e+07,3.651485e+07,1.199938e+08,7.639863e+07,1.199938e+08,1.199938e+08

In [10]:
combined_csv.head()

,Flow Duration,Tot Fwd Pkts,Tot Bwd Pkts,TotLen Fwd Pkts,TotLen Bwd Pkts,Fwd Pkt Len Max,Fwd Pkt Len Min,Fwd Pkt Len Mean,Fwd Pkt Len Std,Bwd Pkt Len Max,...,Fwd Seg Size Min,Active Mean,Active Std,Active Max,Active Min,Idle Mean,Idle Std,Idle Max,Idle Min,Label
1665,410493,1,1,22.0,22.0,22.0,22.0,22.000000,0.000000,22.0,...,0,0.000000,0.000000,0.0,0.0,0.000000e+00,0.000000e+00,0.0,0.0,non_vpn
434,8645898,2,4,306.0,264.0,213.0,93.0,153.000000,84.852814,108.0,...,0,717841.000000,0.000000,717841.0,717841.0,7.582491e+06,0.000000e+00,7582491.0,7582491.0,non_vpn
203,93682019,168,170,15862.0,19471.0,117.0,42.0,94.416667,30.812241,179.0,...,0,8126.666667,103.079258,8232.0,8026.0,2.892348e+07,1.861686e+06,30001130.0,26773792.0,non_vpn
1863,410744,1,1,22.0,22.0,22.0,22.0,22.000000,0.000000,22.0,...,0,0.000000,0.000000,0.0,0.0,0.000000e+00,0.000000e+00,0.0,0.0,non_vpn
65,342,0,2,0.0,175.0,0.0,0.0,0.000000,0.000000,141.0,...,0,0.000000,0.000000,0.0,0.0,0.000000e+00,0.000000e+00,0.0,0.0,non_vpn

In [20]:
combined_csv.replace({'vpn':'1','non_vpn':'0'})

,Flow Duration,Tot Fwd Pkts,Tot Bwd Pkts,TotLen Fwd Pkts,TotLen Bwd Pkts,Fwd Pkt Len Max,Fwd Pkt Len Min,Fwd Pkt Len Mean,Fwd Pkt Len Std,Bwd Pkt Len Max,...,Fwd Seg Size Min,Active Mean,Active Std,Active Max,Active Min,Idle Mean,Idle Std,Idle Max,Idle Min,Label
1665,410493,1,1,22.0,22.0,22.0,22.0,22.000000,0.000000,22.0,...,0,0.000000,0.000000,0.0,0.0,0.000000e+00,0.000000e+00,0.0,0.0,0
434,8645898,2,4,306.0,264.0,213.0,93.0,153.000000,84.852814,108.0,...,0,717841.000000,0.000000,717841.0,717841.0,7.582491e+06,0.000000e+00,7582491.0,7582491.0,0
203,93682019,168,170,15862.0,19471.0,117.0,42.0,94.416667,30.812241,179.0,...,0,8126.666667,103.079258,8232.0,8026.0,2.892348e+07,1.861686e+06,30001130.0,26773792.0,0
1863,410744,1,1,22.0,22.0,22.0,22.0,22.000000,0.000000,22.0,...,0,0.000000,0.000000,0.0,0.0,0.000000e+00,0.000000e+00,0.0,0.0,0
65,342,0,2,0.0,175.0,0.0,0.0,0.000000,0.000000,141.0,...,0,0.000000,0.000000,0.0,0.0,0.000000e+00,0.000000e+00,0.0,0.0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
267,126143,0,2,0.0,187.0,0.0,0.0,0.000000,0.000000,153.0,...,0,0.000000,0.000000,0.0,0.0,0.000000e+00,0.000000e+00,0.0,0.0,1
1946,420841,1,1,22.0,22.0,22.0,22.0,22.000000,0.000000,22.0,...,0,0.000000,0.000000,0.0,0.0,0.000000e+00,0.000000e+00,0.0,0.0,0
198,46480876,3,3,4.0,2.0,2.0,0.0,1.333333,1.154701,2.0,...,0,20891.500000,28987.842495,41389.0,394.0,2.321938e+07,3.659420e+06,25806979.0,20631777.0,0
284,477875,5,5,196.0,180.0,152.0,0.0,39.200000,65.872604,104.0,...,0,0.000000,0.000000,0.0,0.0,0.000000e+00,0.000000e+00,0.0,0.0,0
2415,874,0,2,0.0,410.0,0.0,0.0,0.000000,0.000000,373.0,...,0,0.000000,0.000000,0.0,0.0,0.000000e+00,0.000000e+00,0.0,0.0,1

In [12]:
combined_csv.head()

,Flow Duration,Tot Fwd Pkts,Tot Bwd Pkts,TotLen Fwd Pkts,TotLen Bwd Pkts,Fwd Pkt Len Max,Fwd Pkt Len Min,Fwd Pkt Len Mean,Fwd Pkt Len Std,Bwd Pkt Len Max,...,Fwd Seg Size Min,Active Mean,Active Std,Active Max,Active Min,Idle Mean,Idle Std,Idle Max,Idle Min,Label
1665,410493,1,1,22.0,22.0,22.0,22.0,22.000000,0.000000,22.0,...,0,0.000000,0.000000,0.0,0.0,0.000000e+00,0.000000e+00,0.0,0.0,0
434,8645898,2,4,306.0,264.0,213.0,93.0,153.000000,84.852814,108.0,...,0,717841.000000,0.000000,717841.0,717841.0,7.582491e+06,0.000000e+00,7582491.0,7582491.0,0
203,93682019,168,170,15862.0,19471.0,117.0,42.0,94.416667,30.812241,179.0,...,0,8126.666667,103.079258,8232.0,8026.0,2.892348e+07,1.861686e+06,30001130.0,26773792.0,0
1863,410744,1,1,22.0,22.0,22.0,22.0,22.000000,0.000000,22.0,...,0,0.000000,0.000000,0.0,0.0,0.000000e+00,0.000000e+00,0.0,0.0,0
65,342,0,2,0.0,175.0,0.0,0.0,0.000000,0.000000,141.0,...,0,0.000000,0.000000,0.0,0.0,0.000000e+00,0.000000e+00,0.0,0.0,0

In [19]:
(combined_csv-combined_csv.min())/(combined_csv.max()-combined_csv.min())

TypeError: unsupported operand type(s) for -: 'str' and 'str'

array([[3.42076718e-03, 3.15796122e-05, 0.00000000e+00, ...,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00],
       [7.20491525e-02, 6.31592244e-05, 9.55079431e-05, ...,
        6.31906904e-02, 6.31906904e-02, 0.00000000e+00],
       [7.80683600e-01, 5.30537485e-03, 5.38028079e-03, ...,
        2.50022337e-01, 2.23126463e-01, 0.00000000e+00],
       ...,
       [3.87340683e-01, 9.47388366e-05, 6.36719621e-05, ...,
        2.15069272e-01, 1.71940360e-01, 0.00000000e+00],
       [3.98228393e-03, 1.57898061e-04, 1.27343924e-04, ...,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00],
       [7.27500109e-06, 0.00000000e+00, 3.18359810e-05, ...,
        0.00000000e+00, 0.00000000e+00, 1.00000000e+00]])